[target.riscv64imac-unknown-none-elf]
linker = "ld.lld"
rustflags = [
  "-Clink-arg=--pie",
  "-Clink-arg=--pic-veneer",
  "-Clink-arg=-Bstatic",
  "-Clink-arg=--ignore-function-address-equality",
  "-Clink-arg=--ignore-data-address-equality",
  "-Clink-arg=-zseparate-loadable-segments",
  "-Clink-arg=--pack-dyn-relocs=relr",
]
