[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "mizu"
version = "0.1.0"

[features]
qemu-virt = ["config/qemu-virt"]
default = ["qemu-virt"]

[dependencies]
# Local crates
config = {path = "../lib/config", default-features = false}
rv39-paging = {path = "../lib/paging"}
co-trap = {path = "../lib/co-trap"}
# External crates
r0 = "1"
riscv = "0"
sbi-rt = "0"

[build-dependencies]
config = {path = "../lib/config", default-features = false}
