[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "mizu"
version = "0.1.0"

[dependencies]
# Local crates
rv39-paging = {path = "../lib/paging"}
# External crates
r0 = "1"
riscv = "0"
sbi-spec = "0"
